export const games_list = [
  {
    name: "Game 1",
    studio: "Studio1",
    year: "2020",
    genre: "Genre1",
    PG: "13",
    image: "https://via.placeholder.com/440x100",
    id: "1",
  },
  {
    name: "Game 2",
    studio: "Studio2",
    year: "2018",
    genre: "Genre2",
    PG: "6",
    image: "https://via.placeholder.com/100",
    id: "2",
  },
  {
    name: "Game 3",
    studio: "Studio3",
    year: "2012",
    genre: "Genre3",
    PG: "18",
    image: "https://via.placeholder.com/100",
    id: "3",
  },
  {
    name: "Game 4",
    studio: "Studio4",
    year: "2016",
    genre: "Genre4",
    PG: "12",
    image: "https://via.placeholder.com/100",
    id: "4",
  },
  {
    name: "Game 5",
    studio: "Studio4",
    year: "2016",
    genre: "Genre5",
    PG: "18",
    image: "https://via.placeholder.com/100",
    id: "5",
  },
  {
    name: "Game 21",
    studio: "Studio1",
    year: "2020",
    genre: "Genre1",
    PG: "6",
    image: "https://via.placeholder.com/440x100",
    id: "11",
  },
  {
    name: "Game 22",
    studio: "Studio2",
    year: "2018",
    genre: "Genre2",
    PG: "6",
    image: "https://via.placeholder.com/100",
    id: "7",
  },
  {
    name: "Game 32",
    studio: "Studio3",
    year: "2012",
    genre: "Genre3",
    PG: "18",
    image: "https://via.placeholder.com/100",
    id: "8",
  },
  {
    name: "Game 42",
    studio: "Studio4",
    year: "2016",
    genre: "Genre4",
    PG: "12",
    image: "https://via.placeholder.com/100",
    id: "9",
  },
  {
    name: "Game 52",
    studio: "Studio4",
    year: "2016",
    genre: "Genre5",
    PG: "18",
    image: "https://via.placeholder.com/100",
    id: "10",
  },
  {
    name: "Game next",
    studio: "Studio4",
    year: "2016",
    genre: "Genre5",
    PG: "18",
    image: "https://via.placeholder.com/100",
    id: "132",
  },
  {
    name: "Game SSS",
    studio: "Studio6",
    year: "2021",
    genre: "Genre4",
    PG: "18",
    image: "https://via.placeholder.com/100",
    id: "98",
  },
];
